// Sprite assets — populated after running generate-sprites.js
// Falls back to emoji placeholders if sprites not yet generated
export const SPRITES: Record<string, any> = {
  egg_ember:       require('../../assets/sprites/egg_ember.png'),
  egg_tide:        require('../../assets/sprites/egg_tide.png'),
  egg_void:        require('../../assets/sprites/egg_void.png'),
  egg_storm:       require('../../assets/sprites/egg_storm.png'),
  egg_shadow:      require('../../assets/sprites/egg_shadow.png'),
  egg_crystal:     require('../../assets/sprites/egg_crystal.png'),
  creature_ember:  require('../../assets/sprites/creature_ember.png'),
  creature_tide:   require('../../assets/sprites/creature_tide.png'),
  creature_void:   require('../../assets/sprites/creature_void.png'),
  creature_storm:  require('../../assets/sprites/creature_storm.png'),
  creature_shadow: require('../../assets/sprites/creature_shadow.png'),
  creature_crystal:require('../../assets/sprites/creature_crystal.png'),
};

export const REGIONS = [
  {
    id: 'emberveil',
    name: 'Emberveil Peaks',
    element: 'Ember',
    color: '#ff6b35',
    eggs: 3,
    locked: false,
    x: 0.22,
    y: 0.30,
    description: 'Volcanic highlands where fire-born creatures nest in lava crevices.',
    eggSprite: 'egg_ember',
    creatureSprite: 'creature_ember',
  },
  {
    id: 'tidemarsh',
    name: 'Tidemarsh Delta',
    element: 'Tide',
    color: '#00b4d8',
    eggs: 5,
    locked: false,
    x: 0.58,
    y: 0.62,
    description: 'Vast wetlands shaped by ancient tidal runes, teeming with aquatic hybrids.',
    eggSprite: 'egg_tide',
    creatureSprite: 'creature_tide',
  },
  {
    id: 'voidspire',
    name: 'Voidspire Citadel',
    element: 'Void',
    color: '#9b5de5',
    eggs: 2,
    locked: true,
    x: 0.74,
    y: 0.22,
    description: 'A floating fortress lost between dimensions. Only the rarest bloodlines may enter.',
    eggSprite: 'egg_void',
    creatureSprite: 'creature_void',
  },
  {
    id: 'stormreach',
    name: 'Stormreach Heights',
    element: 'Storm',
    color: '#f7b731',
    eggs: 4,
    locked: false,
    x: 0.40,
    y: 0.72,
    description: 'Storm-wracked plateaus where lightning eggs are charged by perpetual tempests.',
    eggSprite: 'egg_storm',
    creatureSprite: 'creature_storm',
  },
  {
    id: 'gloomfen',
    name: 'Gloomfen Hollow',
    element: 'Shadow',
    color: '#8e7dbe',
    eggs: 1,
    locked: true,
    x: 0.15,
    y: 0.65,
    description: 'A cursed fen where shadow creatures lurk just beyond the veil of sight.',
    eggSprite: 'egg_shadow',
    creatureSprite: 'creature_shadow',
  },
  {
    id: 'crystalpeak',
    name: 'Crystalpeak Summit',
    element: 'Crystal',
    color: '#90e0ef',
    eggs: 6,
    locked: false,
    x: 0.82,
    y: 0.55,
    description: 'Towering crystal spires that amplify and store ancient runic resonance.',
    eggSprite: 'egg_crystal',
    creatureSprite: 'creature_crystal',
  },
];

export const RUNE_SYMBOLS = ['ᚠ', 'ᚢ', 'ᚦ', 'ᚨ', 'ᚱ', 'ᚲ', 'ᚷ', 'ᚹ', 'ᚺ', 'ᚾ', 'ᛁ', 'ᛃ'];

export const PLAYER_STATS = {
  eggsCollected: 12,
  battlesWon: 4,
  creaturesHatched: 7,
};
